import { NgModule } from '@angular/core';
import {
	MatToolbarModule,
	MatSidenavModule,
	MatIconModule,
	MatListModule,
	MatCardModule,
	MatGridListModule,
	MatExpansionModule,
	MatFormFieldModule,
	MatButtonModule,
	MatInputModule,
	MatButtonToggleModule,
	MatSlideToggleModule,
	MatDialogModule,
	MatSnackBarModule,
	MatTooltipModule,
	MatMenuModule,
	MatTabsModule,
	MatRadioModule,
	MatSelectModule,
	MatCheckboxModule,
	MatTableModule,
	MatPaginatorModule,
	MatSortModule,
	MatProgressBarModule,
	MatProgressSpinnerModule,
	MatRippleModule
} from '@angular/material';
import { PortalModule } from '@angular/cdk/portal';
import { DragDropModule } from '@angular/cdk/drag-drop';

@NgModule({
	imports: [
		MatToolbarModule,
		MatSidenavModule,
		MatIconModule,
		MatListModule,
		MatGridListModule,
		MatExpansionModule,
		PortalModule,
		MatFormFieldModule,
		MatCardModule,
		MatButtonModule,
		MatInputModule,
		MatButtonToggleModule,
		MatSlideToggleModule,
		MatDialogModule,
		MatSnackBarModule,
		MatTooltipModule,
		MatMenuModule,
		MatTabsModule,
		MatRadioModule,
		MatSelectModule,
		MatCheckboxModule,
		MatTableModule,
		MatPaginatorModule,
		MatSortModule,
		MatProgressBarModule,
		MatProgressSpinnerModule,
		MatRippleModule,
		DragDropModule
	],
	exports: [
		MatToolbarModule,
		MatSidenavModule,
		MatIconModule,
		MatListModule,
		MatGridListModule,
		MatExpansionModule,
		PortalModule,
		MatFormFieldModule,
		MatCardModule,
		MatButtonModule,
		MatInputModule,
		MatButtonToggleModule,
		MatSlideToggleModule,
		MatDialogModule,
		MatSnackBarModule,
		MatTooltipModule,
		MatMenuModule,
		MatTabsModule,
		MatRadioModule,
		MatSelectModule,
		MatCheckboxModule,
		MatTableModule,
		MatPaginatorModule,
		MatSortModule,
		MatProgressBarModule,
		MatProgressSpinnerModule,
		MatRippleModule,
		DragDropModule
	]
})
export class MaterialModule {}
